#
# Makefile
#

all:

	make trivial_sorts
	make merge_sort
	make quick_sort
	make bucket_sort
	make radix_sort

trivial_sorts:
	make -f trivial_sorts.make

merge_sort:
	make -f merge_sort.make

quick_sort:
	make -f quick_sort.make

bucket_sort:
	make -f bucket_sort.make

radix_sort:
	make -f radix_sort.make